export const SYMBOLS = [
    "NVDA", "AAPL", "MSFT", "AMZN", "GOOG", "META", "TSLA", "BRK.B", "AVGO",
    "WMT", "JPM", "LLY", "V", "UNH", "XOM", "ORCL", "MA", "COST", "HD", "PG", "NFLX",
    "JNJ", "BAC", "CRM", "ABBV", "CVX", "TMUS", "KO", "WFC", "MRK", "BX", "CSCO",
    "ADBE", "AMD", "ACN", "PEP", "NOW", "MS", "LIN", "AXP", "DIS", "MCD", "IBM", "ABT",
    "PM", "GS", "TMO", "GE", "ISRG", "CAT", "VZ", "TXN", "INTU", "QCOM", "BKNG", "DHR",
    "CMCSA", "T", "RTX", "BLK", "SPGI", "LOW", "MDT", "SCHW", "UPS", "NEE", "AMT",
    "PLD", "ELV", "CI", "MO", "DE", "MMC", "MDLZ", "SYK", "AMGN", "GILD", "PFE",
    "LMT", "ADP", "CB", "C", "DUK", "SO", "BDX", "ITW", "EOG", "PNC", "USB", "APD",
    "ADI", "ETN", "FISV", "AON", "BSX", "VRTX", "TGT", "ZTS", "SHW", "REGN", "EW",
    "GM", "F", "NOC", "HUM", "WM", "TRV", "AEP", "PSA", "PSX", "MCO", "ROP", "CCI",
    "NSC", "D", "SBUX", "ORLY", "KLAC", "EQIX", "PGR", "MPC", "ADM", "CTAS", "AIG",
    "BIIB", "SLB", "MRNA", "KMB", "TEL", "HCA", "ECL", "MAR", "MNST", "IDXX", "AZO",
    "ROST", "WBA", "WELL", "SPG", "STZ", "AFL", "ALL", "PRU", "MET", "A", "CDNS",
    "SNPS", "CTSH", "FTNT", "PAYX", "MSCI", "ODFL", "WBD", "WAT", "NEM", "APH", "TT",
    "RMD", "VRSK", "CARR", "OTIS", "HSY", "DLR", "SRE", "PCAR", "MCHP", "ROK", "PH",
    "CTVA", "KMI", "DOW", "BAX", "EMR", "EXC", "GIS", "SYY", "HLT", "BK", "MTD", "FIS",
    "WMB", "ED", "DTE", "PEG", "ES", "EIX", "CMS", "ATO", "NI", "EVRG", "LNT", "PNW",
    "AEE", "CNP", "FE", "PPL", "AES", "NRG", "ETR", "XEL", "DISH", "NWSA", "NWS",
    "FOXA", "FOX", "DISCK", "DISCA", "A", "AAL", "AAP", "ABBV", "ABC", "ABMD", "ACGL",
    "ADI", "ADM", "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG", "AIZ", "AJG",
    "AKAM", "ALB", "ALGN", "ALK", "ALL", "ALLE", "AMAT", "AMCR", "AME", "AMP", "ANET",
    "ANSS", "AON", "AOS", "APA", "APD", "APH", "APTV", "ARE", "ATO", "ATVI", "AVB",
    "AVY", "AWK", "AZO", "BA", "BALL", "BAX", "BBWI", "BBY", "BDX", "BEN", "BF.B",
    "BIIB", "BIO", "BK", "BKR", "BLL", "BMY", "BR", "BRO", "BSX", "BWA", "BXP", "C",
    "CAG", "CAH", "CARR", "CBOE", "CBRE", "CCL", "CDAY", "CDNS", "CDW", "CE", "CF",
    "CFG", "CHD", "CHRW", "CHTR", "CINF", "CL", "CLX", "CMA", "CME", "CMG", "CMI",
    "CMS", "CNC", "CNP", "COF", "COG", "COO", "COP", "CPB", "CPRT", "CPT", "CRL",
    "CSX", "CTAS", "CTLT", "CTRA", "CTSH", "CTXS", "CVS", "CZR", "DAL", "DD", "DFS",
    "DG", "DGX", "DHI", "DISCA", "DISCK", "DISH", "DLR", "DLTR", "DOV", "DOW", "DPZ",
    "DRE", "DRI", "DTE", "DVA", "DVN", "DXC", "DXCM", "EA", "EBAY", "ECL", "ED", "EFX",
    "EIX", "EL", "EMN", "EMR", "ENPH", "EPAM", "EQR", "ESS", "ETN", "ETR", "ETSY",
    "EVRG", "EXC", "EXPD", "EXPE", "EXR", "F", "FANG", "FAST", "FBHS", "FCX", "FDS",
    "FDX", "FE", "FFIV", "FIS", "FITB", "FLIR", "FLS", "FLT", "FMC", "FOX", "FOXA",
    "FRC", "FRT", "FTI", "FTNT", "FTV", "GD", "GE", "GEF", "GILD", "GIS", "GL", "GLW",
    "GM", "GNRC", "GPC", "GPN", "GPS", "GRMN",
];
